### PR TITLE
get stable version from trunk

### PR DESCRIPTION
**Pull request by rafique**

### CODE REVIEW

**Comment by rafique** [comment]
Can you provide with an example plugin/readme that's stable tag set to "trunk"? so that I can test it.

**Comment by nikdow** [comment]
root@ip-172-31-12-147:/home/lamp/wordpress/update_plugins# ./update_plugins.py
checking /home/lamp/wordpress/plugins/ml-slider
url:   http://plugins.svn.wordpress.org/ml-slider/tags/3.15.3
  current tag is 3.15.3 (revision 2201956)
  repo url is http://plugins.svn.wordpress.org/ml-slider
  stable tag found from readme.txt:  3.15.3
checking /home/lamp/wordpress/plugins/if-menu
url:   http://plugins.svn.wordpress.org/if-menu/tags/0.8.3
  current tag is 0.8.3 (revision 1862232)
  repo url is http://plugins.svn.wordpress.org/if-menu
  getting stable tag failed!  [This should work, needs fixing]
checking /home/lamp/wordpress/plugins/thim-testimonials
  not a svn tree  [ this is expected behaviour ]
checking /home/lamp/wordpress/plugins/skilodge-sidebar-login
  not a svn tree [also expected, OK]
checking /home/lamp/wordpress/plugins/wp-recaptcha-integration
url:   http://plugins.svn.wordpress.org/wp-recaptcha-integration/tags/1.3.0
  current tag is 1.3.0 (revision 1747046)
  repo url is http://plugins.svn.wordpress.org/wp-recaptcha-integration
  stable tag found from readme.txt:  1.2.1
Traceback (most recent call last):
  File "./update_plugins.py", line 237, in <module>
    update_svn_trees(plugins)
  File "./update_plugins.py", line 225, in update_svn_trees
    switch_to_svn_tag(tree, repo_url, newest_tags)
NameError: global name 'newest_tags' is not defined
[ This should check out tag 1.2.1 -> at the moment we are running a tag that is not the stable release!!!]

**Comment by nikdow** [comment]
I've restored the initial version and ran it to get the log for you:

Here is an extract:

checking /home/lamp/wordpress/plugins/product-enquiry-for-woocommerce
   http://plugins.svn.wordpress.org/product-enquiry-for-woocommerce/trunk
svn update  '/home/lamp/wordpress/plugins/product-enquiry-for-woocommerce'

Here is the whole log:



So when the URL is for trunk, we must still parse the Stable Release and 
see if the plugin is still on trunk, maybe it migrated to a tag now...

Regards,
_____________________________________________________________________
Nik Dow
Office: +613 9948 4039
Mobile: +614 1270 3483
Between Jan 20th and Feb 20th, call Office only
WhatsApp +61 412 703 483
https://www.gotomeet.me/CBDWeb 
nik@cbdweb.net
907/11-17 Cohen Place, Melbourne, Victoria, Australia

**Comment by nikdow** [comment]
previous message didn't get attachment, 
[output.txt](https://github.com/nikdow/wordpress_plugins/files/4176356/output.txt)

**Pull request merged**
