### PR TITLE
add switch to trunk support

### PR DESCRIPTION
**Pull request by rafique**

### CODE REVIEW

**Comment by nikdow** [comment]
Traceback (most recent call last):
  File "./update_plugins.py", line 248, in <module>
    update_svn_trees(plugins)
  File "./update_plugins.py", line 220, in update_svn_trees
    print '  current tag is %s (revision %d)' % (current_tag, current_rev)

**Comment by nikdow** [comment]
[output2.txt](https://github.com/nikdow/wordpress_plugins/files/4176458/output2.txt)

**Comment by nikdow** [comment]
root@ip-172-31-12-147:/home/lamp/wordpress/plugins# ls
add-search-to-menu                      facebook                           newsletter-reports                      so-widgets-bundle
add-to-any                              facebook-vinyl                     newsletter-woocommerce                  stops-core-theme-and-plugin-updates
add-to-any-subscribe                    favicon-by-realfavicongenerator    nextgen-gallery                         subscribe2
akismet                                 featured-image-caption             opcache-scripts                         subscribe-to-comments-reloaded
allow-multiple-accounts                 features-by-woothemes              optional-email                          tablepress
australian-weather-widget-willyweather  feed-them-social                   paid-memberships-pro                    the-events-calendar
basic-user-avatars                      forget-about-shortcode-buttons     password-strength-for-woocommerce       theme-junkie-shortcodes
bbpress                                 google-analytics-dashboard-for-wp  paypal-donations                        thim-framework
better-font-awesome                     homepage-control                   peters-login-redirect                   thim-testimonials
bj-lazy-load                            if-menu                            pmpro-add-member-admin                  tinymce-advanced
black-studio-tinymce-widget             imagemapper                        pmpro-add-paypal-express                top-10
booking                                 inclusive-parents                  pmpro-email-templates-addon             tp-hotel-booking
booking-manager                         indicate-external-links            pmpro-pay-by-check                      upgrade.sh
broken-link-checker                     insert-headers-and-footers         product-enquiry-for-woocommerce         user-role-editor
category-posts                          jetpack                            projects-by-woothemes                   woocommerce
category-sticky-post                    list-category-posts                reaction-buttons                        woocommerce-admin
cc-child-pages                          loco-translate                     react-webcam                            woocommerce-donation-tip-checkout
cdn-enabler                             media-category-library             redirection                             woocommerce-predictive-search
classic-editor                          media-library-plus                 regenerate-thumbnails                   wordpress-seo
comment-images                          megamenu                           remove-posts-in-category-from-homepage  wp-better-emails
cpt-bootstrap-carousel                  ml-slider                          restrict-content                        wp-block-admin
custom-login                            mobile-menu                        revslider                               wp-external-auth
custom-meta-widget                      nav-menu-roles                     rss-icon-widget                         wp-google-maps
disable-comments                        newsletter                         show-hidecollapse-expand                wp-mail-smtp
download-manager                        newsletter-amazon                  simple-page-sidebars                    wp-mail-smtp-pro
duo-wordpress                           newsletter-archive                 simple-share-buttons-adder              wp-maintenance-mode
duplicate-post                          newsletter-automated               siteorigin-panels                       wp-photo-album-plus
easy-twitter-feed-widget                newsletter-comments                skilodge-sidebar-login                  wp-recaptcha-integration
elementor                               newsletter-facebook                social-warfare                          wp-smushit

**Comment by rafique** [comment]
@nikdow I see only a few lines in output, not all plugins are processed? do you get any error?

**Comment by nikdow** [comment]
yes, previous comment has error message

**Comment by nikdow** [comment]
Are you able to set up a similar directory with some of the plugins checked out (ideally if you can use the same path, the script will work on your machine without change)?

**Comment by rafique** [comment]
It's working fine here. Can you send the full error message please?

Thanks!
Rafique

**Pull request merged**
